export default {
  NW_STATUS_CHANGED: 'NW_STATUS_CHANGED',

  SEND_AUTH_REQUEST: 'SEND_AUTH_REQUEST',
  AUTHORISED: 'AUTHORISED',
  RECONNECT_APP: 'RECONNECT_APP',

  INITIALISE_APP: 'INITIALISE_APP',
  CONNECTED: 'CONNECTED',
  FETCHED_ACCESS_INFO: 'FETCHED_ACCESS_INFO',
  FETCHED_PUBLIC_NAMES: 'FETCHED_PUBLIC_NAMES',
  FETCHED_PUBLIC_CONTAINER: 'FETCHED_PUBLIC_CONTAINER',
  FETCHED_SERVICES: 'FETCHED_SERVICES',
};
