export default {
  NW_STATUS_CHANGED: 'NW_STATUS_CHANGED',

  SEND_AUTH_REQUEST: 'SEND_AUTH_REQUEST',
  AUTHORISED: 'AUTHORISED',
  RECONNECT_APP: 'RECONNECT_APP',
  RESET_AUTHORISATION: 'RESET_AUTHORISATION',

  INITIALISE_APP: 'INITIALISE_APP',
  RESET_INITIALISATION: 'RESET_INITIALISATION',
  CONNECTED: 'CONNECTED',
  FETCHED_ACCESS_INFO: 'FETCHED_ACCESS_INFO',
  FETCHED_PUBLIC_NAMES: 'FETCHED_PUBLIC_NAMES',
  FETCHED_PUBLIC_CONTAINER: 'FETCHED_PUBLIC_CONTAINER',
  FETCHED_SERVICES: 'FETCHED_SERVICES',
  FETCH_SERVICES: 'FETCH_SERVICES',

  SET_PUBLIC_NAMES: 'SET_PUBLIC_NAMES',
  SET_SERVICE_CONTAINERS: 'SET_SERVICE_CONTAINERS',
  CREATE_PUBLIC_NAME: 'CREATE_PUBLIC_NAME',
  FETCH_SERVICE_CONTAINERS: 'FETCH_SERVICE_CONTAINERS',
  RESET_SERVICE_CONTAINERS: 'RESET_SERVICE_CONTAINERS',
  REST_PUBLIC_NAMES: 'REST_PUBLIC_NAMES',

  CHECK_SERVICE_EXIST: 'CHECK_SERVICE_EXIST',
  DELETE_SERVICE: 'DELETE_SERVICE',

  UPLOAD_STARTED: 'UPLOAD_STARTED',
  UPLOAD_COMPLETED: 'UPLOAD_COMPLETED',
  UPLOADING: 'UPLOADING',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  GET_CONTAINER_INFO: 'GET_CONTAINER_INFO',
  PUBLISH: 'PUBLISH',
  RESET_FILE_MANAGER: 'RESET_FILE_MANAGER',
  DELETE_FILE_OR_FOLDER: 'DELETE_FILE_OR_FOLDER',

  RESET: 'RESET'
};
